# .github/workflows/postman-ci.yml

name: Postman API Tests

on: [push, pull_request]

jobs:
  run-newman-tests:
    runs-on: ubuntu-latest # Chạy trên máy chủ Linux ảo
    steps:
      # Bước 1: Lấy code từ repo về
      - name: Lấy code về
        uses: actions/checkout@v4

      # Bước 2: Cài đặt Node.js
      - name: Cài đặt Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18 # Dùng Node 18

      # Bước 3: Cài đặt thư viện cho API (express, cors)
      - name: Cài đặt thư viện API
        run: npm install

      # Bước 4: Cài đặt Newman (công cụ chạy test)
      - name: Cài đặt Newman
        run: npm install -g newman

      # Bước 5: Khởi động API Server (chạy ngầm)
      # Ký tự '&' rất quan trọng, nó cho phép server chạy ngầm
      # để các bước sau có thể tiếp tục
      - name: Khởi động API Server (chạy ngầm)
        run: node server.js & 

      # Bước 6: Chờ API khởi động (Rất quan trọng)
      # Chúng ta cần chờ vài giây để server sẵn sàng nhận request
      - name: Chờ API khởi động (5 giây)
        run: sleep 5

      # Bước 7: Chạy Newman Tests (Lệnh chính của bài)
      # Chạy file .json mà bạn đã export
      - name: Chạy Newman Tests
        run: newman run UniFAQ-API.postman_collection.json